name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  who-to-greet:  # id of input
    description: 'Who to greet'
    required: false
    default: 'World'
  organization:
    required: true
    default: 'SanketPlayground'
  token:
    required: true 
outputs:
  csvArtifactPath:
    description: 'Path to the generated CSV artifact'
runs:
  using: 'node20'
  main: 'dist/index.js'
