name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  who-to-greet:  # id of input
    description: 'Who to greet'
    required: true
    default: 'World'
  organization:
    required: true
    default: 'SanketPlayground'
  token:
    required: true 
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  main: 'dist/index.js'
