on:  
  workflow_dispatch :
    
  push:
    branches: [ main ]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Hello world action step
        id: hello
        uses: SanketPlayground/newAction@main
        with:
          who-to-greet: 'Sanket Desai'
        env:
          organization: ${{secrets.ORG}}
          token: ${{secrets.ACCESS_TOKEN}}
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"
