on:  
  workflow_dispatch :
    
  push:
    branches: [ main ]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Hello world action step
        id: hello
        uses: SanketPlayground/newAction@main
        with:
          who-to-greet: 'Sanket Desai'
          token: ${{secrets.ACCESS_TOKEN}}
        env:
          organization: ${{secrets.ORG}}
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"
      - name: Generate Excel
        id: generate-excel
        run: |
          node -e "require('./path/to/your/index.js').generateExcel()"
        continue-on-error: true # Allow workflow to continue even if this step fails
      
      
      - name: Upload artifact
        uses: actions/upload-artifact@v3.0.0
        with:
          name: generated-alerts
          path: path/to/artifact/content/